DeleteLibrary/Controllers/LibraryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DeleteLibrary.Interfaces;
using DeleteLibrary.Models;
using DeleteLibrary.Services;

namespace DeleteLibrary.Controllers
{
    [Authorize]
    public class LibraryController : Controller
    {
        public IlibraryService _libraryService;

        public LibraryController(IlibraryService libraryService)
        {
            _libraryService = libraryService;
        }
        // GET: Library
        public ActionResult ListFreeBooks()
        {
            var freeBooks = _libraryService.GetListFreeBooks();
            return View(freeBooks);
        }

        public ActionResult ReservedBook(int Id)
        {
            var takenBook = new TakenBook
            {
                BookId = Id,
                UserId = _libraryService.GetUserByLogin(User.Identity.Name).Id, //Здесь нужно поставить пользователя, который авторезирован
                IsReserved = true
            };
            _libraryService.RemoveTakenBookByBookId(Id);
           _libraryService.CreateTakenBook(takenBook);
           
            return RedirectToAction("ListFreeBooks");
        }

        public ActionResult ListMyBooks()
        {
            var TakenBooks = _libraryService.GetTakenBooksByUserId(_libraryService.GetUserByLogin(User.Identity.Name).Id);
            return View(TakenBooks);
        }
        public ActionResult ListReservedMyBooks()
        {
            var reservedTakenBooks = _libraryService.GetReservedTakenBooksByUserId(_libraryService.GetUserByLogin(User.Identity.Name).Id);
            return View(reservedTakenBooks);
        }

        public ActionResult ListAllBooks()
        {
            var takenBooks = _libraryService.GetAllTakenBooks();
            return View(takenBooks);
        }

        public ActionResult HistoryMyAllTakenBooks()
        {
            var allTakenBook = _libraryService.GetAllOnDeletedTakenBooks().Where(m=>m.User.Login==User.Identity.Name).ToArray();
            return View(allTakenBook);
        }
        //public ActionResult SearchBook(string searchString)
        //{
        //    var takenBooks = _libraryService.GetAllTakenBooks();
        //    takenBooks.Select(m => m.Book.Name.Contains(searchString)); 
        //    return View("~/Views/Library/ListAllBooks.cshtml",takenBooks);
        //}
    }
}

DeleteLibrary/Views/Library/HistoryMyAllTakenBooks.cshtml
@model DeleteLibrary.Models.TakenBook[]
<table class="table table-bordered table-hover table-striped table-condensed">
    <tr>
        <th>Название книги</th>
        <th>Обложка</th>
        <th>Дата получения</th>
        <th>Дата возврата</th>
    </tr>
    @foreach (var takenBook in Model)
    {
        <tr>
            <td>@takenBook.Book.Name</td>
            <td><img class="img-size" src="@takenBook.Book.Cover" /></td>
            <td>@takenBook.DateTake</td>
            <td>@takenBook.DateReturn</td>
        </tr>
    }
</table>

DeleteLibrary/Views/Library/ListAllBooks.cshtml
@model DeleteLibrary.Models.TakenBook[]
@*@using (Html.BeginForm("SearchBook", "Library", FormMethod.Get, new { @class = "form-control" })) { 
<p>
    <input type="text" name="searchString" placeholder="поиск по названию" />
    <input type="submit" value="поиск" />
</p>
}*@
@foreach (var takenBook in Model)
{
    <div class="list-book">
        <div class="row">
            <div class="col-md-3 book-list-header">
                <div class="name-books-list"><b>@takenBook.Book.Name</b></div>
            </div>
            <div class="col-md-9 book-list-header">
                <b>Книга находится у: @takenBook.User.Name</b>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">

                <img class="img-rounded img-books-list" src="@takenBook.Book.Cover">
                <div>
                    <div class="author-books-list">Автор:@takenBook.Book.Author</div>
                </div>
            </div>

            <div class="col-md-9">
                <div class="book-description">
                    @takenBook.Book.Discription
                </div>
            </div>
        </div>
    </div>
}

DeleteLibrary/Views/Library/ListFreeBooks.cshtml
@model DeleteLibrary.Models.Book[]

@foreach (var book in Model)
{

    <div class="list-book">
        <div class="row">
            <div class="col-md-3 book-list-header">
                <div class="name-books-list"><b>@book.Name</b></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <img class="img-rounded img-books-list" src="@book.Cover">
                <div>
                    <div class="author-books-list">Автор:@book.Author</div>
                </div>
            </div>

            <div class="col-md-9">
                <div class="book-description">
                    @book.Discription
                </div>
                <div>
                    @Html.ActionLink("Забронировать книгу", "ReservedBook", "Library", new { Id = book.Id }, new { @class = "btn btn-block btn-success" })
                </div>
            </div>
        </div>
    </div>
}

DeleteLibrary/Views/Library/ListMyBooks.cshtml
@model DeleteLibrary.Models.TakenBook[]

@foreach (var takenBook in Model)
{

    <div class="list-book">
        <div class="row">
            <div class="col-md-3 book-list-header">
                <div class="name-books-list"><b>@takenBook.Book.Name</b></div>
            </div>
            <div class="col-md-9 book-list-header">
                <b>Дата выдачи: @takenBook.DateTake</b>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">

                <img class="img-rounded img-books-list" src="@takenBook.Book.Cover">
                <div>
                    <div class="author-books-list">Автор:@takenBook.Book.Author</div>
                </div>
            </div>

            <div class="col-md-9">
                <div class="book-description">
                    @takenBook.Book.Discription
                </div>
            </div>
        </div>
    </div>
}

DeleteLibrary/Views/Library/ListReservedMyBooks.cshtml
@model DeleteLibrary.Models.TakenBook[]

@foreach (var takenBook in Model)
{
    <div class="list-book">
        <div class="row">
            <div class="col-md-3 book-list-header">
                <div class="name-books-list"><b>@takenBook.Book.Name</b></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">

                <img class="img-rounded img-books-list" src="@takenBook.Book.Cover">
                <div>
                    <div class="author-books-list">Автор:@takenBook.Book.Author</div>
                </div>
            </div>

            <div class="col-md-9">
                <div class="book-description">
                    @takenBook.Book.Discription
                </div>
            </div>
        </div>
    </div>
}